### ISSUE TITLE
[Enhancement/Feature] Isolated chunk viewing

### ISSUE THREAD

**Issue by LimblessVector** [igorseabra4/HeroesPowerPlant#38]
It can be hard to tell which chunks correspond to what number, which is relevant for .bdt and .fog file editing. It would be nice if the user could quickly select a chunk and view it and its chunk boxes in isolation.

- Allow a chunk box to be selected by clicking it in the render view while Chunk Boxes are enabled.
- A toggle for hiding all unselected chunks and their chunk boxes. If the selected chunk box's chunk has multiple chunk boxes, then they would still show.

**Comment by dreamsyntax** [comment]
@LimblessVector 
This was partially implemented in https://github.com/igorseabra4/HeroesPowerPlant/commit/428bfcd5374562778bfb84a96e0f003f329d711b 

You can now select/deselect geometry in the level editor to show/hide it, but it does not necessarily correspond to the BLK / chunk box.

![image](https://user-images.githubusercontent.com/14857235/189792126-2f55b114-6265-4e6d-b2d0-d2a2e3a41c7a.png)
