### ISSUE TITLE
[Bug] Saving Project does not add .json extension

### ISSUE THREAD

**Issue by dreamsyntax** [igorseabra4/HeroesPowerPlant#41]
Project -> Save or Save As...

Typing in the file name and saving will save exactly as typed.

## Current
"example" -> example

## Expected
"example" -> example.json

**Comment by dreamsyntax** [comment]
Can be fixed by adding
"DefaultExt" to the Dialog object. Example below using Ookii (note it may not be using Ookii in HPP)

```csharp
            Ookii.Dialogs.Wpf.VistaSaveFileDialog dialog = new Ookii.Dialogs.Wpf.VistaSaveFileDialog {
                FileName = TextBlock_AfsAudioIDName.Text,
                DefaultExt = ".adx",
                Filter = "ADX files (*.adx)|*.adx|WAV files (*.wav)|*.wav|All files (*.*)|*.*"
            };
```

**Comment by blouflashdb** [comment]
Would like to work on this.

**Comment by dreamsyntax** [comment]
> Would like to work on this.

Feel free, open a PR referencing this issue. Thank you
